name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # Add testing pipeline here
        
      - name: Build and Restart Application
        run: |
          docker compose up -d --build