name: Sync Flows on VM

on:
  push:
    branches: [main]
    paths:
      - 'prefect_workflows/**'

jobs:
  git-pull:
    name: Pull latest code on VM
    runs-on: self-hosted
    steps:
      - name: Git pull
        run: git -C "${{ github.workspace }}" pull
